apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  {{- if not .Values.nextcloud.autoscaling.enabled }}
  replicas: {{ .Values.nextcloud.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.nextcloud.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "nextcloud.serviceAccountName" . | quote }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.nextcloud.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.nextcloud.image.name }}:{{ .Values.nextcloud.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nextcloud.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nextcloud.service.fpm.port }}
          {{- with .Values.nextcloud.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.nextcloud.resources | nindent 12 }}
          volumeMounts:
            - name: fpm-config
              mountPath: /usr/local/etc/php-fpm.d
            - name: nextcloud-app
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
          env:
            - name: REDIS_HOST
              value: {{ printf "%s-master" (include "common.names.fullname" .) }}
              # charts/redis-18.0.1.tgz!/redis/charts/common/templates/_names.tpl:26
            - name: POSTGRES_HOST
              value: {{ include "postgresql.primary.fullname" . }}
              # charts/postgresql-12.10.0.tgz!/postgresql/templates/_helpers.tpl:12
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret | quote }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret | quote }}
                  key: password
            - name: PHP_UPLOAD_LIMIT
              value: 5120M
            - name: PHP_POST_LIMIT
              value: 5120M
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: cloud.neumanny.live nextcloud.pictaviensis.regnum
            - name: TRUSTED_PROXIES
              value: cloud.neumanny.live 172.104.150.140 10.42.0.0/15
            - name: OVERWRITEHOST
              value: cloud.neumanny.live
            - name: OVERWRITEPROTOCOL
              value: https
        {{- if .Values.nextcloud.service.http.enabled }}
        - name: nginx
          image: "{{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nextcloud.service.http.port }}
          {{- with .Values.nginx.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 16Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nextcloud-app
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-tmp
              mountPath: /var/tmp/nginx
        {{- end }}
      volumes:
        - name: fpm-config
          configMap:
            name: fpm
        - name: nginx-config
          configMap:
            name: nginx
        - name: nextcloud-app
          persistentVolumeClaim:
            claimName: nextcloud-app
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-tmp
          persistentVolumeClaim:
            claimName: nextcloud-tmp
      {{- with .Values.nextcloud.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nextcloud.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nextcloud.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
