{{- if .Values.nextcloud.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nextcloud.fullname" . }}
  minReplicas: {{ .Values.nextcloud.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.nextcloud.autoscaling.maxReplicas | default 4 }}
  {{- with .Values.nextcloud.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- if .Values.nextcloud.autoscaling.averageCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nextcloud.autoscaling.averageCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.nextcloud.autoscaling.averageMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.nextcloud.autoscaling.averageMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
