apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-redis"
spec:
  storageClassName: "manual"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: "Delete"
  capacity:
    storage: "256Mi"
  hostPath:
    path: "/mnt/ssd/nextcloud-redis"