apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nextcloud-tmp"
spec:
  storageClassName: "manual"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  volumeName: "nextcloud-tmp"