apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "redis"
spec:
  storageClassName: "manual"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "256Mi"
  volumeName: "nextcloud-redis"
