apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nextcloud-data"
  annotations:
    nfs.io/storage-path: "nextcloud-data"
spec:
  storageClassName: {{ .Values.global.persistence.nfsHddStorageClassName | quote }}
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "768Gi"