apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "postgresql"
spec:
  storageClassName: "local-storage"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"
  volumeName: "nextcloud-postgresql"
