apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nextcloud-tmp"
spec:
  storageClassName: "local-storage"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  volumeName: "nextcloud-tmp"
