apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: nextcloud
    metallb.universe.tf/allow-shared-ip: nextcloud-svc
spec:
  type: {{ .Values.nextcloud.service.type }}
  ports:
    {{- if .Values.nextcloud.service.http.enabled }}
    - port: {{ .Values.nextcloud.service.http.port }}
      targetPort: {{ .Values.nextcloud.service.http.port }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.nextcloud.service.fpm.enabled }}
    - port: {{ .Values.nextcloud.service.fpm.port }}
      targetPort: {{ .Values.nextcloud.service.fpm.port }}
      protocol: TCP
      name: fpm
    {{- end }}
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
